                                     ############################
                                     ## un-crafter config file ##
                                     ############################



# HOW TO USE IMPORTANT:
# in un-craft: list go down and add 2 spaces then add - then 1 space
# type the id of item that will be uncrafted , then add =  WITHOUT ANY SPACES
# then type the drops id such as Leather add # WITHOUT ANY SPACES and add number of how many to drop
# then make another drop by add & WITHOUT ANY SPACES  and follow the line above
# make another item to be uncrafted the same way under your previous item

# it is not creator fault if you did not follow instructions correctly or put a false id



# here the list add your stuff
un-craft:
  - 'saddle=leather#3&iron_ingot#1'
  - 'Iron_pickaxe=stick#2&iron_ingot#3'
