name: Uncraft
version: ${project.version}
main: uncraft.mythicmc.zorioux.uncraft.Uncraft
authors: [Zorioux]
description: Uncraft your items that modified in config
website: Mythicmc.info/forums
commands:
  uncraft:
    description: custom uncraft
  uncraft-reload:
    description: reloads config in game or in console !

